name: PR Size

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pattern: "{__sapper__/export/**/*.css,__sapper__/export/**/*.js}"
          build-script: "export"
